[LogFile]
linesInBlock = 1000
maxBlocks = 10
rootDir = "c:\\Users\\kot\\loganal\\realtest"
logName = "test"
#logPathRegex = /mnt/c/Users/kot/loganal/realtest/test.log*
logPathRegex = c:\\Users\\kot\\loganal\\realtest\\test.log*
rarityThreshold = 0.8
frequencyCheck = true
frequencyThreshold = 0.2
minSupportPerBlock = 0.02
absencyThreshold = 0.5
logLevel = debug